server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db,ping
#  health:
#    db:
#      enabled: true
#    livenessstate:
#      enabled: true
#    readinessstate:
#      enabled: true

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework: info
    sql: info

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://mysql:3306/petclinic
    username: root
    password: petclinic
  test:
    database:
      replace: none
  messages:
    basename: messages/messages
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 12h
  lifecycle:
    timeout-per-shutdown-phase: 20s
