apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
#  annotations:
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: spring-petclinic-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: raphael-test.stg.kurly.services
      http:
        paths:
          - backend:
              service:
                name: spring-petclinic
                port:
                  number: 8080
            path: /
            pathType: Prefix
